### ISSUE TITLE
Delete file after deleting the sound

### ISSUE THREAD

**Issue by lowski** [gamebooster/soundboard#25]
when deleting a sound through the api the downloaded file should be deleted as well @skomski

**Comment by skomski** [comment]
no

**Comment by lowski** [comment]
not deleting it prevents you from adding it again, bc the download will fail and not overwrite the existing file

**Comment by skomski** [comment]
okay overwrite

cadast <notifications@github.com> schrieb am So., 12. Juli 2020, 17:33:
