### ISSUE TITLE
Option to add custom Google Speech API key

### ISSUE THREAD

**Issue by camjac251** [gamebooster/soundboard#42]
Using v0.1.0 (since v0.1.1 doesn't have manifests), I get this error when attempting to use the tts features
```
ERROR soundboard::sound] get_local_path_from_sound_config failed: tts: failed to synthesize speech: status: PermissionDenied, message: "This API method requires billing to be enabled. Please enable billing on project 
```

Could it be possible to give it a custom oauth token in the config or command line arguments?

**Comment by skomski** [comment]
fixed 98b2f79106f175fe1d8d2d550b13d83e540966bd
