### ISSUE TITLE
Support youtube videos as source

### ISSUE THREAD

**Issue by skomski** [gamebooster/soundboard#6]
* use youtube-dl for getting the audio link
* new decoder needed: either extract vorbis audio from webm container or use m4a

**Comment by docweirdo** [comment]
https://docs.rs/rafy/0.2.1/rafy/
This might be a suitable library, I found other rust libraries to be lacking functionality.
youtube-dl for example only fetches metadata and no actual video or sound content

**Comment by skomski** [comment]
3b710416db503a22ce35a3d8ba94467f390495be
